= Списак коришћених скраћеница

#table(
  columns: 2,
  [*Скраћеница*], [*Опис*],
  [AMQP], [`Advanced Message Queuing Protocol` (протокол за размену порука)],
  [API], [`Application Programming Interface` (апликациони програмски интерфејс)],
  [AST], [`Abstract Syntax Tree` (апстрактно синтаксно стабло)],
  [AWS], [`Amazon Web Services` (Амазон веб сервиси)],
  [CI/CD], [`Continuous Integration / Continuous Delivery` (континуирана интеграција / континуирана испорука)],
  [CLI], [`Command Line Interface` (команднолинијски интерфејс)],
  [CORS], [`Cross-Origin Resource Sharing` (размена ресурса између извора различитог порекла)],
  [DTO], [`Data Transfer Object` (објекат за пренос података)],
  [GDPR], [`General Data Protection Regulation` (Општа уредба о заштити података)],
  [HTTP / HTTPS], [`HyperText Transfer Protocol (Secure)` (протокол за пренос хипертекста)],
  [I/O], [`Input/Output` (улаз/излаз)],
  [JSON], [`JavaScript Object Notation` (формат за размену података)],
  [JWT], [`JSON Web Token` (безбедносни токен заснован на JSON формату)],
  [LLM], [`Large Language Model` (велики језички модел)],
  [ML], [`Machine Learning` (машинско учење)],
  [ONNX], [`Open Neural Network Exchange` (отворен формат за размену модела машинског учења)],
  [QL], [`Query Language` (упитни језик, у контексту CodeQL)],
  [RAM], [`Random Access Memory` (меморија са случајним приступом)],
  [REST], [`Representational State Transfer` (скуп правила за комуникацију клијент-сервер)],
  [SOC 2], [`Service Organization Control 2` (стандард усклађености за безбедност података)],
  [SPA], [`Single Page Application` (једнострана веб апликација)],
  [SQL], [`Structured Query Language` (структурирани упитни језик)],
  [TLS], [`Transport Layer Security` (безбедност транспортног слоја)],
  [URL], [`Uniform Resource Locator` (јединствени локатор ресурса)],
  [UI], [`User Interface` (кориснички интерфејс)],
  [UUID], [`Universally Unique Identifier` (универзално јединствени идентификатор)],
  [UTF-8], [`Unicode Transformation Format – 8-bit` (формат кодирања текста)],
  [XSS], [`Cross-Site Scripting` (напад убацивањем скрипти кроз веб страницу)],
  [YAML], [`YAML Ain't Markup Language` (формат за серијализацију података)],
  [ZIP], [назив формата за компресију и архивирање фајлова],
)
