[package]
name = "suggestion_generator_service"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
axum = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
dotenvy = { workspace = true }
anyhow = { workspace = true }
uuid = { workspace = true }
chrono = { version = "0.4", features = ["serde"] }
mongodb = { version = "3.1" }
bson = { version = "2.9", features = ["chrono-0_4", "uuid-1"] }
tower = "0.4"
tower-http = { version = "0.5", features = ["cors"] }

lapin = "2.3"
futures-lite = "1.13"