[package]
name = "api_gateway"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
axum = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
dotenvy = { workspace = true }
anyhow = { workspace = true }
uuid = { workspace = true }

reqwest = { version = "0.11", features = ["json"] }
jsonwebtoken = "9"
tower = "0.4"
tower-http = { version = "0.5", features = ["cors", "auth"] }

lapin = "2.3"